[log]
output = "stderr"
level = "debug"

[supervisor]
name = "continually-restarting-sleeper"

[health_check]
listen_addr = "127.0.0.1:3000"

[worker]
count = 3
type = "program"
cmdline = ["bundle", "exec", "--gemfile", "gems/kleinhirn_loader/examples/sleeper_agent/Gemfile", "--keep-file-descriptors",
           "ruby", "gems/kleinhirn_loader/examples/sleeper_agent/sleeper_agent.rb"]
ack_workers = true
env = {}