[log]
output = "stderr"
format = {format = "json"}
level = "debug"

[health_check]
listen_addr = "127.0.0.1:3000"

[supervisor]
name = "nc-as-a-program"

[worker]
type = "program"
cmdline = ["nc", "-vvvl", "127.0.0.1", "8000"]
cwd = "/"
env = {}