# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Metrics:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/LineLength:
  Max: 120
  AllowURI: true
  AllowHeredoc: true

Name/MethodParameterName:
  MinNameLength: 2

Style/IfUnlessModifier:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantBegin:
  Enabled: false
